services:
  # Production에서는 Postgres를 외부에 노출하지 않도록 비활성화
  postgres:
    ports: []

  server:
    # 프로덕션에서는 애플리케이션 포트를 호스트의 루프백(127.0.0.1)으로만 바인딩
    # Nginx가 동일 EC2에서 127.0.0.1:8080으로 프록시
    ports:
      - "127.0.0.1:8080:8080"
